"""add streak fields to users

Revision ID: 04da00290eab
Revises: e6e96ece08cf
Create Date: 2026-02-21 09:46:39.383129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '04da00290eab'
down_revision: Union[str, Sequence[str], None] = 'e6e96ece08cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('streak_count', sa.Integer(), server_default='0', nullable=True))
    op.add_column('users', sa.Column('last_active_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_active_date')
    op.drop_column('users', 'streak_count')
    # ### end Alembic commands ###
